version: '3'
services:
    nginx:
        image: nginx:1.17
        ports:
            - "80:80"
            - "443:443"
        volumes:
#            - ./docker/web:/etc/nginx/conf.d
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./public:/srv/app/public:ro
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        links:
            - php
        restart: unless-stopped
#        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    php:
        image: bitnami/php-fpm:7.4
        ports:
            - 9000
        volumes:
            - ./:/srv/app
        restart: unless-stopped
    db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
        restart: unless-stopped
    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
#        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"