version: '3'
services:
#    traefik:
#        # The official v2 Traefik docker image
#        image: traefik:v2.2
#        container_name: traefik
#        # Enables the web UI and tells Traefik to listen to docker
#        command:
#            - --api.insecure=true # <== Enabling insecure api, NOT RECOMMENDED FOR PRODUCTION
#            - --providers.docker=true # <== Enabling docker as provider for traefik
#            - --proviers.docker.exposedbydefault=false # <== Don't expose every container to traefik, only expose enabled ones
#            - --providers.docker.network=web # <== Operate an entrypoint for port :80 named web
#            - --entrypoints.web.address=:80 # <== Defining an entrypoint for port :80 named web
#        ports:
#            # The HTTP port
#            - "80:80"
#        volumes:
#            # So that Traefik can listen to the Docker events
#            - /var/run/docker.sock:/var/run/docker.sock
#        networks:
#            - web
#        restart: unless-stopped
    web:
        image: nginx:1.17
        ports:
            - "80:80"
        volumes:
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./public:/srv/app/public:ro
        links:
            - php
#        networks:
#            - web
#        labels:
#            - "traefik.enable=true" # <== Enable traefik to proxy for this container
#            - "traefik.http.routers.nginx-web.rule=Host('flowchartapp.de')" # <== Domain for Http rule
#            - "traefik.http.routers.nginx-web.entrypoints=web" # <== Defining an entrypoint for http
        restart: unless-stopped
    php:
        image: bitnami/php-fpm:7.4
        ports:
            - 9000
        volumes:
            - ./:/srv/app
        restart: unless-stopped
    db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
        restart: unless-stopped

#networks:
#    web:
#        external: true
