version: '3'
services:
    nginx:
        image: nginx:1.17
        ports:
            - "80:80"
        expose:
          - 80
        volumes:
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./public:/srv/app/public:ro
        links:
            - php
        restart: unless-stopped
    php:
        image: bitnami/php-fpm:7.4
        ports:
            - 9000
        volumes:
            - ./:/srv/app
        restart: unless-stopped
        working_dir: /srv/app
    db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
        restart: unless-stopped
