version: '3'
services:
#    traefik:
#        image: "traefik:v2.2"
#        container_name: "traefik"
#        command:
#            #- "--log.level=DEBUG"
#            - "--api.insecure=true"
#            - "--providers.docker=true"
#            - "--providers.docker.exposedbydefault=false"
#            - "--entrypoints.flowchartapp.address=:80"
#        ports:
#            - "80:80"
#            - "8080:8080"
#        volumes:
#            - "/var/run/docker.sock:/var/run/docker.sock:ro"
    nginx:
        image: nginx:1.17
#        ports:
#            - "80:80"
        expose:
          - 80
        environment:
          - VIRTUAL_HOST= flowchartapp.de
          - LETSENCRYPT_HOST= flowchartapp.de
          - LETSENCRYPT_EMAIL= julius_schulze1996@web.de
        volumes:
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./public:/srv/app/public:ro
        links:
            - php
        restart: unless-stopped
#        labels:
#            - "traefik.enable=true"
#            - "traefik.http.routers.flowchartapp.rule=Host(`flowchartapp.de`)"
#            - "traefik.http.routers.flowchartapp.entrypoints=flowchartapp"
    php:
        image: bitnami/php-fpm:7.4
        ports:
            - 9000
        volumes:
            - ./:/srv/app
        restart: unless-stopped
    db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
        restart: unless-stopped
networks:
    default:
        external:
            name: nginx-proxy